"""Transcript tokenization and TR-alignment interfaces."""

from structure_comparison._implementation import (
    TokenWordGroup,
    TranscriptPaths,
    TranscriptTokenStream,
    TrBin,
    WordTiming,
    aggregate_tr_feature_views,
    assign_words_to_trs,
    build_token_to_word_index,
    extract_global_tokens,
    group_tokens_into_words,
    group_tokens_with_model_tokenizer,
    infer_word_start_marker,
    load_tr_bins,
    load_word_rows,
    normalize_text,
    resolve_transcript_paths,
    validate_tr_alignment,
    validate_word_alignment,
)

__all__ = [
    "TokenWordGroup",
    "TranscriptPaths",
    "TranscriptTokenStream",
    "TrBin",
    "WordTiming",
    "aggregate_tr_feature_views",
    "assign_words_to_trs",
    "build_token_to_word_index",
    "extract_global_tokens",
    "group_tokens_into_words",
    "group_tokens_with_model_tokenizer",
    "infer_word_start_marker",
    "load_tr_bins",
    "load_word_rows",
    "normalize_text",
    "resolve_transcript_paths",
    "validate_tr_alignment",
    "validate_word_alignment",
]
